### ISSUE TITLE
Unable to Build as per Instruction on AWS AMI Scylla Image

### ISSUE THREAD

**Issue by Sen-Gupta** [scylladb/scylla-bench#105]
We were trying to benchmark scyalla on AWS AMI Image as recommended.

We followed the steps to install but we could not build.

root@~# cd scylla-bench/
root@:~/scylla-bench# go install .
go: downloading github.com/scylladb/gocql v1.7.2
go: downloading github.com/hailocab/go-hostpool v0.0.0-20160125115350-e80d13ce29ed
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/HdrHistogram/hdrhistogram-go v1.1.2
go: downloading github.com/golang/snappy v0.0.3
go: downloading gopkg.in/inf.v0 v0.9.1
github.com/gocql/gocql
../go/pkg/mod/github.com/scylladb/gocql@v1.7.2/dial.go:79:18: tconn.HandshakeContext undefined (type *tls.Conn has no field or method HandshakeContext)**
root@~/scylla-bench# cylla-bench -workload sequential -mode write -nodes 127.0.0.1
cylla-bench: command not found
root@:~/scylla-bench# scylla-bench -workload sequential -mode write -nodes 127.0.0.1
scylla-bench: command not found
root@~/scylla-bench# scylla-bench
scylla-bench: command not found
root@~/scylla-bench# scylla-bench
scylla-bench: command not found
root@~/scylla-bench# go install .
github.com/gocql/gocql
../go/pkg/mod/github.com/scylladb/gocql@v1.7.2/dial.go:79:18: tconn.HandshakeContext undefined (type *tls.Conn has no field or method HandshakeContext)

**Comment by fruch** [comment]
using the supported go versions does work
