### ISSUE TITLE
Extend scylla-bench to create tables (keyspaces) with tablets enabled

### ISSUE THREAD

**Issue by avelanarius** [scylladb/scylla-bench#132]
Tablets is an upcoming feature of ScyllaDB. Keyspaces created with tablets (https://github.com/scylladb/scylladb/blob/master/docs/cql/ddl.rst#the-tablets-property-label-cautionexperimental) organize the data in a different fashion than regular ring-based keyspaces. Scylla-bench should be extended to be able to create keyspaces with tablets enable so we can better test this functionality.

**Comment by fruch** [comment]
@xemul do we really need this with modern scylla ?

**Comment by xemul** [comment]
We still need to start Scylla with `--experimental-feature tablets` (and `consistent-topology-chagnes`). Not more than that tough

**Comment by avelanarius** [comment]
> Not more than that tough

I'm not sure I follow you - this issue is just about making sure that scylla-bench can emit `CREATE KEYSPACE ... WITH ... AND tablets = {'initial': X}` - that the tool has some command line argument to control that.

**Comment by avelanarius** [comment]
Or is there some setting in Scylla that turns it on by default for all new keyspaces? (I missed this if this was added)

**Comment by fruch** [comment]
> Or is there some setting in Scylla that turns it on by default for all new keyspaces? (I missed this if this was added)

see https://github.com/scylladb/scylladb/pull/16364

so to enable tablets one needs only to enable the feature.

if you want to change the numbers of `initial`, you can use the keyspace creation for that.

we can overcome that as well in SCT for example, and pre create the schema (we already have code for that. s-b schema isn't that complex, and doesn't change much)

so it's a nice to have feature, to pass in extra arguments to create schema, but not a must

**Comment by roydahan** [comment]
I don't think there is a need to support tablets in any of the tools at the moment.
If a such a need arises, we can reopen this to discussion.

**Comment by mykaul** [comment]
> I don't think there is a need to support tablets in any of the tools at the moment. If a such a need arises, we can reopen this to discussion.

Why not? @roydahan - I fail to see the reason we would not have it in all tools.

**Comment by roydahan** [comment]
I fail to see why the client would need to define it from the client side.
Like many other schema parameters we don't control from the outside.

If there is a demand for the long term to test it with various configurations, it will make sense.
