### ISSUE TITLE
Concurrency flag behaves completely wrong when the "concurrency" is larger than the number of partitions in sequential mode

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-bench#138]
https://github.com/scylladb/scylla-bench/blob/e87621070b86ad0c8e1d7ae78500414c55895f14/main.go#L137-L146

In case the user supplies: "-partition-count=50" and "-concurrency=100" it seems that the first 99 threads won't do anything and the last thread will read all partitions.

**Comment by vponomaryov** [comment]
Fix is here:
- https://github.com/scylladb/scylla-bench/pull/153
