### ISSUE TITLE
random/random_test.go: use list for test-case instead of map

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla-bench#17]
Lists ensure fixed execution order of the test cases, each time they are ran.
Example: https://github.com/jmoiron/sqlx/blob/master/named_test.go#L9

**Comment by rjeczalik** [comment]
I don't see what we gain by introducing this - usually one wants the test (and test-case) execution to be random - randomisation gives us confidence, that written tests (and test-cases) do not depend on each other.

One can quasi-randomise test order by use of (*testing.T).Parallel, using maps here is randomising test-case execution.

**Comment by mmatczuk** [comment]
I share opinion of the two gentlemen below:

```
This is an easy change to make but seems odd to me.  If a randomized
test finds a bug, it means your tests aren't good enough.  You
shouldn't celebrate randomness so much as figure out why you needed
those conditions to trigger the bug and recreate them in a
deterministic test.
I'm not thrilled about this idea, but I'm also not dead set against
it.  I do worry about flagging up gotest, making it a complex mess,
because it's easier to do that than to write good tests.  Gotest's
main virtue, which is a Very Big one, is its utter simplicity. It's a
testing tool; let's no turn it into a testing development environment.

-rob
```

```
Randomizing the order in which tests run is a
very very weak amount of randomness.
If you really want multiple possible executions
out of rand, why not seed the generator yourself?
Russ
```

https://groups.google.com/forum/#!topic/golang-dev/W6fTX9axlaI

**Comment by rjeczalik** [comment]
I don't see how those relate - I'm not advocating that it's better to have random tests than good tests, all I'm saying is that there's non-zero probability that random test-case execution will break some test somewhere on CI on n-th run if the test-cases are not idempotent to tested code. Even assuming the probability is so low that it wouldn't happen, I don't see a benefit of a sequential test-cases.

Go maintainers are trying to protect `go test` from unnecessary additions and I understand their standpoint.

**Comment by mmatczuk** [comment]
> I don't see how those relate

It relates to your comment in the PR

> Somewhat related - not sure if it landed, but there was a bug for testing package to support test shaking to randomise the order. Using maps gives us that for free.

For this probably it does not matter and we could close this issue, randomization here has no effect.
