### ISSUE TITLE
scylla-bench exit silently before duration expired, there is no error notification related to time of exit.

### ISSUE THREAD

**Issue by shoshan** [scylladb/scylla-bench#38]
scylla-bench exit silently before duration without error notification in time of exit.
duration is 6420m, scyllabench exits about 20H later.

longevity-large-partition-200k-pks-4days-test test_id: 9dcfc92c-8c7f-4527-bd11-3507b351160c

**start command of scylla-bench**
`
2020-11-11 18:42:51.328: (ScyllaBenchEvent Severity.NORMAL): type=start node=Node longevity-large-partitions-200k-pks-loader-node-9dcfc92c-3 [54.75.56.236 | 10.0.2.213] (seed: False) stress_cmd=scylla-bench -workload=sequential -mode=read -replication-factor=3 -partition-count=1000 -clustering-row-count=100000 -clustering-row-size=uniform:3072..5120 -rows-per-request=10 -consistency-level=quorum -timeout=90s -concurrency=100 -connection-count=100 -duration=6420m

**Summary of the run**
`
< t:2020-11-12 14:36:47,139 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > 1h13m10.507279065s             5242    26690        0  32.899071ms      30.441471ms      20.578303ms      5.996543ms       4.259839ms       1.769471ms       2.56633ms        
< t:2020-11-12 14:36:47,140 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > Results
< t:2020-11-12 14:36:47,140 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > Time (avg):        12h34m0.22769027s
< t:2020-11-12 14:36:47,140 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > Total ops:         99999969

`

**premature closing of scylla-bench**
`
< t:2020-11-12 14:36:43,547 f:cluster.py      l:1345 c:sdcm.cluster         p:DEBUG > 2020-11-12T14:36:43+00:00  longevity-large-partitions-200k-pks-db-node-9dcfc92c-5 !ERR     | sshd[25144]: error: AuthorizedKeysCommand /opt/aws/bin/eic_run_authorized_keys centos SHA256:g7OmDbWC8qLUZHxjMohQe3LsQHfcOJbG1ZHqodB6smc f
ailed, status 22
ailed, status 22
< t:2020-11-12 14:36:47,139 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > 1h13m10.507279065s             5242    26690        0  32.899071ms      30.441471ms      20.578303ms      5.996543ms       4.259839ms       1.769471ms       2.56633ms        
< t:2020-11-12 14:36:47,140 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > Results
< t:2020-11-12 14:36:47,140 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > Time (avg):        12h34m0.22769027s
< t:2020-11-12 14:36:47,140 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > Total ops:         99999969
< t:2020-11-12 14:36:47,140 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > Total rows:        230735508
< t:2020-11-12 14:36:47,140 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > Total errors:      31
< t:2020-11-12 14:36:47,140 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > Operations/s:      2933.629783137083
< t:2020-11-12 14:36:47,140 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > Rows/s:            13594.324435091936
< t:2020-11-12 14:36:47,140 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > Latency:
< t:2020-11-12 14:36:47,140 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   max:             2.009071615s
< t:2020-11-12 14:36:47,140 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   99.9th:  20.676607ms
< t:2020-11-12 14:36:47,140 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   99th:            8.716287ms
< t:2020-11-12 14:36:47,140 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   95th:            4.358143ms
< t:2020-11-12 14:36:47,140 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   90th:            3.080191ms
< t:2020-11-12 14:36:47,140 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   median:  1.015807ms
< t:2020-11-12 14:36:47,140 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   mean:            1.60965ms
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > STDERR: 2020/11/11 18:46:11 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 18:46:17 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 18:46:21 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 18:46:23 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 18:46:25 Operation failed for scylla_bench.test - received 1 responses and 1 failures from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 18:46:29 Operation failed for scylla_bench.test - received 1 responses and 1 failures from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 18:46:31 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 18:46:41 Operation failed for scylla_bench.test - received 1 responses and 1 failures from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 18:46:47 Operation failed for scylla_bench.test - received 1 responses and 1 failures from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 18:46:49 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 18:46:51 Operation failed for scylla_bench.test - received 1 responses and 1 failures from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 18:46:53 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 18:50:09 Operation failed for scylla_bench.test - received 1 responses and 1 failures from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 19:09:45 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 19:09:47 Operation failed for scylla_bench.test - received 1 responses and 1 failures from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 19:09:49 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 19:13:37 Operation failed for scylla_bench.test - received 1 responses and 1 failures from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 19:17:55 EOF
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 19:17:55 EOF
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 19:17:55 EOF
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 19:23:24 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 19:30:16 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 19:30:56 error: failed to connect to 10.0.1.156:9042 due to error: gocql: no response received from cassandra within timeout period
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 19:41:19 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 19:41:19 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 19:44:32 Operation failed for scylla_bench.test - received 1 responses and 1 failures from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 19:44:34 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 19:44:36 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 19:44:38 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 21:09:26 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 21:09:31 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 21:09:36 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 21:09:41 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 21:09:46 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 21:10:06 error: failed to connect to 10.0.1.156:9042 due to error: gocql: no response to connection startup within timeout
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 21:11:47 error: failed to connect to 10.0.1.156:9042 due to error: gocql: no response received from cassandra within timeout period
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 21:12:06 error: failed to connect to 10.0.1.156:9042 due to error: gocql: no response received from cassandra within timeout period
< t:2020-11-12 14:36:47,156 f:base.py         l:138  c:RemoteCmdRunner      p:DEBUG > 2020/11/11 22:44:47 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
< t:2020-11-12 14:36:47,156 f:base.py         l:140  c:RemoteCmdRunner      p:DEBUG > Command "/$HOME/go/bin/scylla-bench -workload=sequential -mode=read -replication-factor=3 -partition-count=1000 -clustering-row-count=100000 -clustering-row-size=uniform:3072..5120 -rows-per-request=10 -consistency-level=quorum -timeout=90s -concurrency=100 -connection-count=100 -duration=6420m -nodes 10.0.1.45" finished with status 0
< t:2020-11-12 14:36:47,167 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  > 2020-11-12 14:36:47.156: (ScyllaBenchEvent Severity.NORMAL): type=finish node=Node longevity-large-partitions-200k-pks-loader-node-9dcfc92c-3 [54.75.56.236 | 10.0.2.213] (seed: False) stress_cmd=scylla-bench -workload=sequential -mode=read -replication-factor=3 -partition-count=1000 -clustering-row-count=100000 -clustering-row-size=uniform:3072..5120 -rows-per-request=10 -consistency-level=quorum -timeout=90s -concurrency=100 -connection-count=100 -duration=6420m
< t:2020-11-12 14:36:51,578 f:connectionpool.py l:204  c:urllib3.connectionpool p:DEBUG > Starting new HTTP connection (1): 10.0.2.226:9093

sct.log:1004651:< t:2020-11-12 14:36:47,167 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  > 2020-11-12 14:36:47.156: (ScyllaBenchEvent Severity.NORMAL): type=finish node=Node longevity-large-partitions-200k-pks-loader-node-9dcfc92c-3 [54.75.56.236 | 10.0.2.213] (seed: False) stress_cmd=scylla-bench -workload=sequential -mode=read -replication-factor=3 -partition-count=1000 -clustering-row-count=100000 -clustering-row-size=uniform:3072..5120 -rows-per-request=10 -consistency-level=quorum -timeout=90s -concurrency=100 -connection-count=100 -duration=6420m
`

**Comment by roydahan** [comment]
Can you please add here the result summary of the run?

I remember it was saying 12h and 999999 (or something similar) ops.

**Comment by roydahan** [comment]
@juliayakovlev is it possible that if it complete reading all the records it doesn’t respect the duration flag?

Can you try it with tiny dataset?
Few records and seconds/minutes?

**Comment by roydahan** [comment]
This is not an issue, we found out that we must use -iteration=0 for scylla-bench to use the duration.
