### ISSUE TITLE
Implement retry option

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-bench#63]
Make it possible s-b to retry failed operation on the same data

**Comment by dkropachev** [comment]
In order to get there we need to refactor modes.go:

- implement mode interface
- put mode parameters and state into structure
- implement each mode as instance of the interface
- split current mode body into query/data generation and test execution
- find a way to exclude data validation from retrying

**Comment by vponomaryov** [comment]
Implemented here: https://github.com/scylladb/scylla-bench/pull/96
