### ISSUE TITLE
Support for HdrHistogram.

### ISSUE THREAD

**Issue by pveentjer** [scylladb/scylla-bench#67]
Add support for HdrHistogram for recording the latency distribution.

https://github.com/HdrHistogram/hdrhistogram-go

Cassandra-stress uses this library/format as well.

There are 2 big advantages of hdr histogram:
- it doesn't record a latency histogram for the whole run, but you can configure it to record a latency histogram for e.g. every second in a run. This way we can track latency over time.
- when stored to disk, we can use other hdr tools to merge the histograms of different  scylla-bench instances for example and do other magic like pruning, filtering etc etc.

**Comment by dkropachev** [comment]
Implemented here - https://github.com/scylladb/scylla-bench/pull/75
