### ISSUE TITLE
timeseries read: wrong partition key generator

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla-bench#7]
Most of partition keys produced by key generator for timeseries read are non-existing, so an empty reads  distort latency metrics

**Comment by slivne** [comment]
@larisau can you please provide sample parameters that you used that did not work for you

**Comment by larisau** [comment]
write:
scylla-bench -workload=timeseries -mode=write -replication-factor=3 -partition-count=150000 -clustering-row-count=86400 -clustering-row-size=200 -concurrency=48 -max-rate=150000 -rows-per-request=5000

read:
scylla-bench -workload=timeseries -mode=read -partition-count=150000 -concurrency=1 -replication-factor=3 -write-rate=150000 -clustering-row-count=86400 -clustering-row-size=200 -rows-per-request=86400 -no-lower-bound -start-timestamp=1530479761791927831

**Comment by roydahan** [comment]
@slivne @pdziepak, is it something we can fix soon?
We want to automate a test with time-series.

**Comment by pdziepak** [comment]
`-write-rate` in the read command is wrong, it should be the value reported by `scylla-bench` which is in this case 1.

**Comment by larisau** [comment]
With a valid write-rate value all works as expected. Closing the issue.
